---
# This playbook deploys a set of Jenkins slaves to test various Hibernate projects
# It also deploys the basic setup for the Jenkins master node, but most
# configuration of this node is not automated.

- hosts: awscislaves
  remote_user: fedora
  become: yes

  roles:
    - common
    - aws
    - jenkins-common
    - jenkins-slave
    - awsslave
    - postgres-server
    - mariadb-server
    - redis-server
    - neo4j-server
    - cockroachdb-server


- hosts: cimaster
  remote_user: ec2-user
  become: yes

  roles:
    - common
    - aws
    - jenkins-common
    - jenkins-master

- hosts: websites
  remote_user: ec2-user
  become: yes

  roles:
    - common
    - aws
    - websites
