---

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "http://pkg.jenkins-ci.org/redhat/jenkins.repo"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key"

- name: Get Jenkins, OpenJDK 8 and other common dependencies
  yum: name={{item}} state=present
  with_items:
   - unzip
   - java-1.8.0-openjdk-devel
   - git
   - curl
   - gnupg
   - wget
   - sendmail
   - which
   - jenkins
  when: ansible_pkg_mgr == 'yum'

# Now install Apache HTTPD
- name: install the latest version of Apache HTTPD
  yum: name=httpd state=latest
  when: ansible_pkg_mgr == 'yum'

- name: Make sure the example welcome page from HTTPD is removed
  file: path=/etc/httpd/conf.d/{{ item }} state=absent
  with_items:
    - autoindex.conf
    - userdir.conf
    - welcome.conf

- name: Custom Jenkins configuration
  copy: src=jenkins-config dest=/etc/sysconfig/jenkins mode=0600 owner=root

- name: Ensure Jenkins is started now, and again on startup
  service: name=jenkins enabled=yes state=started

- name: Add custom HTTPD configuration (common)
  copy: src=httpd-config dest=/etc/httpd/conf.d/catchall.conf mode=0600 owner=root

- name: Reconfigure SELinux to allow HTTPD to forward requests to Jenkins
  command: setsebool -P httpd_can_network_connect 1

- name: Ensure Apache HTTPD is started now, and again on startup
  service: name=httpd enabled=yes state=restarted
