---

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "https://pkg.jenkins.io/redhat-stable/jenkins.io.key"

- name: Install Jenkins, HTTPD, OpenJDK
  dnf:
    name: ['java-11-openjdk-devel', 'jenkins', 'httpd', 'mod_ssl']
    state: present

- name: Copy custom CSS for CI
  copy: src=jenkins/userContent/ci-hibernate.css dest=/var/lib/jenkins/userContent/ mode=0700 owner=jenkins group=jenkins
  tags:
    - copy-css

- name: Copy Hibernate logo for CI
  copy: src=jenkins/userContent/hibernate-logo.svg dest=/var/lib/jenkins/userContent/ mode=0700 owner=jenkins group=jenkins
  tags:
    - copy-css

- name: Ensure Jenkins is started now, and again on startup
  service: name=jenkins enabled=yes state=started

- name: Make sure the example welcome page from HTTPD is removed
  file: path=/etc/httpd/conf.d/{{ item }} state=absent
  with_items:
    - autoindex.conf
    - userdir.conf
    - welcome.conf

- name: Custom Jenkins configuration
  copy: src=etc/sysconfig/jenkins dest=/etc/sysconfig/jenkins mode=0600 owner=root

- name: Add custom HTTPD configuration (ci.hibernate.org)
  copy: src=etc/httpd/ci.hibernate.org.conf dest=/etc/httpd/conf.d/ci.hibernate.org.conf mode=0600 owner=root

- name: Reconfigure SELinux to allow HTTPD to forward requests to Jenkins
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

# Doesn't currently work because we're using an unregistered RHEL for some reason,
# and repos containing necessary dependencies are disabled
#- name: Install the latest version of Let's Encrypt's "certbot", using dnf
#  dnf:
#    name: ['certbot', 'certbot-apache']
#    state: latest

- name: Obtain certificates for ci.hibernate.org using Let's Encrypt
  shell: sudo certbot certonly --apache -d ci.hibernate.org
  args:
    creates: /etc/letsencrypt/live/ci.hibernate.org

- name: Ensure Let's encrypt certificates get renewed
  cron:
    name: "Renew let's encrypt certificates"
    minute: "0"
    hour: "0,12"
    job: "python -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/local/bin/certbot-auto renew"

- name: Ensure Apache HTTPD is started now, and again on startup
  service: name=httpd enabled=yes state=restarted

