---

# Fetch the public key of this node
- fetch: src=/home/jenkins/.ssh/hostkey.pub dest=/tmp/publicdeployedkeys/pubkey-ci-master.pub flat=yes fail_on_missing=yes
  tags:
    - crosskeyauthentication
    - fetch-keys

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "http://pkg.jenkins-ci.org/redhat/jenkins.repo"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"

- name: Ensure Jenkins is installed
  yum: name=jenkins state=present

- name: Ensure Jenkins is started now, and again on startup
  service: name=jenkins enabled=yes state=started

# Copy custom css 
- name: Copy custom CSS for CI
  copy: src=ci-hibernate-v0012.css dest=/var/lib/jenkins/userContent/ mode=0700 owner=jenkins group=jenkins
  tags:
    - copy-css

# Now install Apache HTTPD
- name: install the latest version of Apache HTTPD
  yum: name=httpd state=latest

- name: Make sure the example welcome page from HTTPD is removed
  file: path=/etc/httpd/conf.d/{{ item }} state=absent
  with_items:
    - autoindex.conf
    - userdir.conf
    - welcome.conf

- name: Custom Jenkins configuration
  copy: src=jenkins-config dest=/etc/sysconfig/jenkins mode=0600 owner=root

- name: Add custom HTTPD configuration (common)
  copy: src=httpd-common-config dest=/etc/httpd/conf.d/common.conf mode=0600 owner=root

- name: Add custom HTTPD configuration (ci.hibernate.org)
  copy: src=httpd-ci-hibernate-org-config dest=/etc/httpd/conf.d/ci-hibernate-org.conf mode=0600 owner=root

- name: Add custom HTTPD configuration (staging.hibernate.org)
  copy: src=httpd-staging-hibernate-org-config dest=/etc/httpd/conf.d/staging-hibernate-org.conf mode=0600 owner=root

- name: Reconfigure SELinux to allow HTTPD to forward requests to Jenkins
  command: setsebool -P httpd_can_network_connect 1

- name: Ensure Apache HTTPD is started now, and again on startup
  service: name=httpd enabled=yes state=restarted

- name: Generate the script to synchronize tools on slaves
  template: src=transfer-to-slaves-script dest=/home/jenkins/transfer-to-slaves.sh owner=jenkins group=jenkins mode=0700
  tags:
    - generate-script

- name: Generate the script to copy ssh keys
  template: src=transfer-ssh-keys-script dest=/home/jenkins/transfer-ssh-to-slaves.sh owner=root group=root mode=0705
  tags:
    - generate-script

