---

# Install PostgreSQL Server, setup testing databases and accounts
- name: Ensure PostgreSQL Server is installed
  dnf: name=postgresql-server state=present
  tags:
    - postgres

- name: Python adapters for PostgreSQL are installed
  dnf: name=python3-psycopg2 state=present
  tags:
    - postgres

- name: Setup authentication methods
  copy: src=pg_hba.conf dest=/var/lib/pgsql/data/pg_hba.conf owner=postgres group=postgres mode=0600
  notify: Reload PostgreSQL
  tags:
    - postgres

- name: Apply some tuning suited for unit tests
  copy: src=postgresql.conf dest=/var/lib/pgsql/data/postgresql.conf owner=postgres group=postgres mode=0600
  notify: Reload PostgreSQL
  tags:
    - postgres

- name: Initiate PostgreSQL database if needed
  command: /usr/bin/postgresql-setup --initdb
    creates=/var/lib/pgsql/data/postgresql.conf
  tags:
    - postgres

- name: Ensure PostgreSQL Server is started now, and again on startup
  service: name=postgresql enabled=yes state=started
  tags:
    - postgres

- name: Create PostgreSQL database testingdb
  postgresql_db: name=testingdb state=present
  become: yes
  become_user: postgres 
  tags:
    - postgres

- name: Create PostgreSQL database hibernate_orm_test
  postgresql_db: name=hibernate_orm_test state=present
  become: yes
  become_user: postgres 
  tags:
    - postgres

- name: Create hibernate_user account in PostgreSQL
  postgresql_user: db=testingdb name=hibernate_user password=hibernate_password priv=ALL
  become: yes
  become_user: postgres 
  tags:
    - postgres

- name: Create hibernate_orm_test account in PostgreSQL
  postgresql_user: db=hibernate_orm_test name=hibernate_orm_test password=hibernate_orm_test priv=ALL
  become: yes
  become_user: postgres 
  tags:
    - postgres

- name: Set privileges for PostgreSQL's hibernate_user account
  postgresql_user: name=hibernate_user role_attr_flags=NOCREATEDB,NOSUPERUSER
  become: yes
  become_user: postgres 
  tags:
    - postgres

- name: Set privileges for PostgreSQL's hibernate_orm_test account
  postgresql_user: name=hibernate_orm_test role_attr_flags=SUPERUSER
  become: yes
  become_user: postgres 
  tags:
    - postgres

- name: Check credentials for hibernate_orm_test
  shell: psql -d hibernate_orm_test -U hibernate_orm_test -h 127.0.0.1 -c 'SELECT 1';
  environment:
    PGPASSWORD: 'hibernate_orm_test'
  tags:
    - postgres-validation
    - postgres

- name: Check credentials for hibernate_user
  shell: psql -d testingdb -U hibernate_user -h 127.0.0.1 -c 'SELECT 1';
  environment:
    PGPASSWORD: 'hibernate_password'
  tags:
    - postgres-validation
    - postgres
