---

- name: Install all package upgrades
  yum: name=* state=latest
  notify:
     - Restart server
     - Wait for server to restart

- name: Get OpenJDK 8 and other common dependencies
  yum: name={{item}} state=present
  with_items:
   - unzip
   - java-1.8.0-openjdk-devel
   - git
   - curl
   - gnupg
   - wget
   - sendmail
   - which
   - mc
   - vim

# Create the jenkins user and explicitly set gid and uid
- group: name=jenkins state=present gid=1001
- user: name=jenkins comment="Jenkins user" shell=/bin/bash state=present generate_ssh_key=yes uid=1001

# Fetch the public key of this node
- fetch: src=/home/jenkins/.ssh/id_rsa.pub dest=/tmp/publicdeployedkeys/pubkey-{{ ansible_hostname }} flat=yes fail_on_missing=yes

- name: Setup SSH config for Github authentication
  copy: src=sshconfig dest=/home/jenkins/.ssh/config mode=0600 owner=jenkins group=jenkins

- name: Setup Github as a known host
  copy: src=github-knownhosts dest=/home/jenkins/.ssh/github-knownhosts mode=0600 owner=jenkins group=jenkins

# Install Maven 3.2.5

- name: Download Maven
  get_url:
    url=http://www.mirrorservice.org/sites/ftp.apache.org/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz
    dest=/home/jenkins/apache-maven-3.2.5-bin.tar.gz

- file: path=/home/jenkins/apache-maven-3.2.5-bin.tar.gz owner=jenkins group=jenkins mode=0644

- name: Install Maven
  unarchive:
    src=/home/jenkins/apache-maven-3.2.5-bin.tar.gz
    dest=/home/jenkins/
    copy=no
    creates=/home/jenkins/apache-maven-3.2.5
    group=jenkins
    owner=jenkins

- name: Add .bashrc for jenkins
  copy: src=.bashrc dest=/home/jenkins/.bashrc mode=0600 owner=jenkins group=jenkins

