---
# Configure journald
- name: Apply journald configuration for minimum overhead and storage costs
  copy: src=journald.conf dest=/etc/systemd/journald.conf owner=root group=root mode=0644
  notify: Restart journald
  tags:
    - journald

- name: Remove old journald stored logs from disk
  file: path=/var/log/journal state=absent
  tags:
    - journald

# Update and install packages, using dnf
- name: Install all package upgrades using dnf
  dnf:
    name: "*"
    state: latest
  notify:
     - Restart server
     - Wait for server to restart

# Hostname and hosts file
- name: Set the hostname
  hostname: name={{ hostname }}
  tags:
    - hostname

- name: Setup the hosts file to workaround Java RMI limitations
  template: src=hosts dest=/etc/hosts
  tags:
    - hostname

# Create the jenkins user and explicitly set gid and uid
- group: name=jenkins state=present gid=1001
- user: name=jenkins comment="Jenkins user" shell=/bin/bash state=present generate_ssh_key=yes uid=1001 ssh_key_type=ecdsa ssh_key_bits=521 ssh_key_file=.ssh/hostkey ssh_key_comment="cimaster-hostkey" password_lock=true
  tags:
    - crosskeyauthentication

- name: Setup SSH config
  copy: src=sshconfig dest=/home/jenkins/.ssh/config mode=0600 owner=jenkins group=jenkins

- name: Setup Github as a known host
  copy: src=github-knownhosts dest=/home/jenkins/.ssh/github-knownhosts mode=0600 owner=jenkins group=jenkins

- name: Setup SourceForge as a known host
  copy: src=sourceforge-knownhosts dest=/home/jenkins/.ssh/sourceforge-knownhosts mode=0600 owner=jenkins group=jenkins

- name: Setup filemgmt.boss.org as a known host
  copy: src=filemgmt-knownhosts dest=/home/jenkins/.ssh/filemgmt-knownhosts mode=0600 owner=jenkins group=jenkins

- name: Add .bashrc for jenkins
  copy: src=.bashrc dest=/home/jenkins/.bashrc mode=0600 owner=jenkins group=jenkins
