---
- name: Install Postfix
  dnf:
    name: "postfix"
    state: latest
  tags:
    - postfix

- name: Ensure Postfix Server is started now, and again on startup
  service: name=postfix enabled=yes state=started
  tags:
    - postfix

# Create the jenkins user and explicitly set gid and uid
- group: name=jenkins state=present gid=1001
- user: name=jenkins comment="Jenkins user" shell=/bin/bash state=present generate_ssh_key=yes uid=1001 ssh_key_type=ecdsa ssh_key_bits=521 ssh_key_file=.ssh/hostkey ssh_key_comment="cimaster-hostkey" password_lock=true

- name: Setup SSH config
  copy: src=sshconfig dest=/home/jenkins/.ssh/config mode=0600 owner=jenkins group=jenkins

- name: Setup Github as a known host
  copy: src=github-knownhosts dest=/home/jenkins/.ssh/github-knownhosts mode=0600 owner=jenkins group=jenkins

- name: Setup SourceForge as a known host
  copy: src=sourceforge-knownhosts dest=/home/jenkins/.ssh/sourceforge-knownhosts mode=0600 owner=jenkins group=jenkins

- name: Setup filemgmt.boss.org as a known host
  copy: src=filemgmt-knownhosts dest=/home/jenkins/.ssh/filemgmt-knownhosts mode=0600 owner=jenkins group=jenkins

- name: Add .bashrc for jenkins
  copy: src=.bashrc dest=/home/jenkins/.bashrc mode=0600 owner=jenkins group=jenkins
