---

- name: install the latest version of Redis
  yum: name=redis state=latest

- name: Deploy our Redis Configuration
  copy: src=redis.conf dest=/etc/redis.conf owner=root group=root mode=0644
  notify:
     - Restart Redis

- name: Ensure Redis started now, and again on reboot
  service: name=redis enabled=yes state=started

